version: '3'

services:
  laravel-app:
    build: .
    ports:
    - "8080:80"
    volumes: 
    - ./:/usr/share/nginx
  mysql-app:
    image: mysql:latest
    command: --innodb-use-native-aio=0
    ports: 
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge